project:
  type: website
  output-dir: docs
  resources:
    - "images/**"

website:
  title: "Vidhi Vashishth"
  navbar:
    left:
      - href: index.qmd
        text: "About Me"
      - resume.qmd
      - href: blog.qmd
        text: Thoughts

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



