project:
  type: website
  output-dir: docs

website:
  title: "Vidhi Vashishth"
  navbar:
    left:
      - index.qmd
      - resume.qmd
      - href: blog.qmd
        text: Thoughts

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



