<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.5">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vidhi Vashishth">

<title>A Replication of Karlan and List (2007) – Vidhi’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ff4371ef257df69894857e99c6ad0d06.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d1b3a47244d1cc36f22d9f8a6971822f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Vidhi’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">Description</a></li>
  <li><a href="#key-features-of-the-dataset" id="toc-key-features-of-the-dataset" class="nav-link" data-scroll-target="#key-features-of-the-dataset">Key Features of the Dataset</a></li>
  <li><a href="#balance-test" id="toc-balance-test" class="nav-link" data-scroll-target="#balance-test">Balance Test</a></li>
  <li><a href="#demonstration-t-test-vs.-regression-approach" id="toc-demonstration-t-test-vs.-regression-approach" class="nav-link" data-scroll-target="#demonstration-t-test-vs.-regression-approach">Demonstration: T-test vs.&nbsp;Regression Approach</a></li>
  <li><a href="#interpretation-of-balance-tests" id="toc-interpretation-of-balance-tests" class="nav-link" data-scroll-target="#interpretation-of-balance-tests">Interpretation of Balance Tests</a></li>
  </ul></li>
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results">Experimental Results</a>
  <ul class="collapse">
  <li><a href="#charitable-contribution-made" id="toc-charitable-contribution-made" class="nav-link" data-scroll-target="#charitable-contribution-made">Charitable Contribution Made</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#differences-between-match-rates" id="toc-differences-between-match-rates" class="nav-link" data-scroll-target="#differences-between-match-rates">Differences between Match Rates</a></li>
  <li><a href="#interpretation-of-match-ratio-effects" id="toc-interpretation-of-match-ratio-effects" class="nav-link" data-scroll-target="#interpretation-of-match-ratio-effects">Interpretation of Match Ratio Effects</a></li>
  <li><a href="#size-of-charitable-contribution" id="toc-size-of-charitable-contribution" class="nav-link" data-scroll-target="#size-of-charitable-contribution">Size of Charitable Contribution</a></li>
  <li><a href="#interpretation-of-donation-amount-analysis" id="toc-interpretation-of-donation-amount-analysis" class="nav-link" data-scroll-target="#interpretation-of-donation-amount-analysis">Interpretation of Donation Amount Analysis</a></li>
  </ul></li>
  <li><a href="#simulation-experiment" id="toc-simulation-experiment" class="nav-link" data-scroll-target="#simulation-experiment">Simulation Experiment</a>
  <ul class="collapse">
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers">Law of Large Numbers</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Replication of Karlan and List (2007)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Vidhi Vashishth </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>.</p>
<p>This natural field experiment was designed to investigate a fundamental question in the economics of charity: Does price matter in charitable giving? While previous research has examined price effects through tax deductibility and rebate mechanisms, this study specifically explores whether, and to what extent, matching grants affect donor behavior. Matching grants effectively lower the “price” of donating by increasing the impact of each dollar contributed.</p>
<p>The experiment involved a direct mail solicitation to 50,083 prior donors to a liberal nonprofit organization working on social and policy issues related to civil liberties. The sample was randomly divided, with 33,396 individuals (67 percent) assigned to a treatment “match” group and 16,687 individuals (33 percent) assigned to a control group. All individuals received identical four-page letters except for two key differences: treatment letters included an additional paragraph announcing that a “concerned fellow member” would match their donation, and the reply card highlighted the match details in bold type.</p>
<p>The study incorporated three experimental variations:</p>
<ul>
<li>Match Ratio: The price ratio of the match varied between $1:$1, $2:$1, and $3:$1 ratios</li>
<li>Maximum Size: The maximum amount of the matching gift across all donations varied between $25,000, $50,000, $100,000, and unstated</li>
<li>Example Amount: The suggested donation amount used to illustrate the match effect varied between the individual’s highest previous contribution, 1.25 times that amount, and 1.50 times that amount.</li>
</ul>
<p>The findings provide several important insights into charitable giving behavior: First, the mere presence of a matching offer significantly increased both the revenue per solicitation (by 19 percent) and the probability of donating (by 22 percent). Surprisingly, however, larger match ratios ($3:$1 and $2:$1) relative to a smaller match ratio ($1:$1) had no additional impact on giving behavior. Secondly, the study also revealed intriguing heterogeneous treatment effects based on political environment: the matching gift was highly effective in Republican-leaning “red” states (increasing revenue per solicitation by 55 percent) but had little effect in Democratic-leaning “blue” states.</p>
<p>This project seeks to replicate their results, and explore their implications for our understanding of charitable giving, price sensitivity, and the private provision of public goods.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<p>This dataset contains information from a charitable giving field experiment conducted by Karlan and List (2007). The experiment tests whether matching grants increase charitable donations, both on the extensive margin (whether people donate) and the intensive margin (how much they donate).</p>
<div id="data-load" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code for loading and preparing data</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import necessary libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the data file</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_stata(<span class="st">"Data.dta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The dataset includes 50083 observations from a direct mail solicitation to prior donors of a nonprofit organization. The experiment randomly assigned potential donors to either a control group (no matching grant) or one of several treatment groups with different match ratios (1:1, 2:1, or 3:1) and different match thresholds.</p>
<div class="cell" data-tbl-cap="Summary Statistics for Key Variables" data-execution_count="2">
<div id="data-summary" class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Summary Statistics for Key Variables</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">treatment</th>
<th data-quarto-table-cell-role="th">control</th>
<th data-quarto-table-cell-role="th">gave</th>
<th data-quarto-table-cell-role="th">amount</th>
<th data-quarto-table-cell-role="th">hpa</th>
<th data-quarto-table-cell-role="th">freq</th>
<th data-quarto-table-cell-role="th">years</th>
<th data-quarto-table-cell-role="th">mrm2</th>
<th data-quarto-table-cell-role="th">dormant</th>
<th data-quarto-table-cell-role="th">female</th>
<th data-quarto-table-cell-role="th">couple</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>50083.000</td>
<td>50083.000</td>
<td>50083.000</td>
<td>50083.000</td>
<td>50083.000</td>
<td>50083.000</td>
<td>50082.000</td>
<td>50082.000</td>
<td>50083.000</td>
<td>48972.000</td>
<td>48935.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>0.667</td>
<td>0.333</td>
<td>0.021</td>
<td>0.916</td>
<td>59.385</td>
<td>8.039</td>
<td>6.098</td>
<td>13.007</td>
<td>0.523</td>
<td>0.278</td>
<td>0.092</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>0.471</td>
<td>0.471</td>
<td>0.142</td>
<td>8.707</td>
<td>71.180</td>
<td>11.394</td>
<td>5.503</td>
<td>12.081</td>
<td>0.499</td>
<td>0.448</td>
<td>0.289</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>30.000</td>
<td>2.000</td>
<td>2.000</td>
<td>4.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>1.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>45.000</td>
<td>4.000</td>
<td>5.000</td>
<td>8.000</td>
<td>1.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>1.000</td>
<td>1.000</td>
<td>0.000</td>
<td>0.000</td>
<td>60.000</td>
<td>10.000</td>
<td>9.000</td>
<td>19.000</td>
<td>1.000</td>
<td>1.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
<td>400.000</td>
<td>1000.000</td>
<td>218.000</td>
<td>95.000</td>
<td>168.000</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div>

</div>
<div id="cell-treatment-distribution" class="cell quarto-layout-panel" data-layout-ncol="2" data-execution_count="3">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="treatment-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/treatment-distribution-output-1.png" width="757" height="469" class="figure-img"></p>
<figcaption>Distribution of Treatment and Control Groups</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="treatment-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/treatment-distribution-output-2.png" width="757" height="469" class="figure-img"></p>
<figcaption>Distribution of Match Ratios in Treatment Group</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div id="cell-threshold-distribution" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_28735/2497486154.py:3: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="threshold-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/threshold-distribution-output-2.png" width="949" height="469" class="figure-img"></p>
<figcaption>Distribution of Match Thresholds in Treatment Group</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="key-features-of-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="key-features-of-the-dataset">Key Features of the Dataset</h3>
<p>The dataset has approximately 67% of observations in the treatment group and 33% in the control group. Among the treatment observations, subjects were evenly divided among the three match ratios (1:1, 2:1, 3:1) and four threshold conditions ($25,000, $50,000, $100,000, and Unstated).</p>
<p>Key variables include:</p>
<ul>
<li><code>treatment</code>: Indicator for receiving any matching offer</li>
<li><code>control</code>: Indicator for control group</li>
<li><code>gave</code>: Binary indicator of whether a donation was made</li>
<li><code>amount</code>: Amount donated (in dollars)</li>
<li><code>ratio</code>: Match ratio (1, 2, or 3 corresponding to 1:1, 2:1, and 3:1)</li>
<li><code>size</code>: Match threshold amount</li>
<li>Donor characteristics: highest previous amount (<code>hpa</code>), frequency of prior donations (<code>freq</code>), years since first donation (<code>years</code>), months since most recent donation (<code>mrm2</code>), gender (<code>female</code>), and more.</li>
</ul>
<p>The overall donation rate in the sample is only about 2%, which is typical for direct mail fundraising campaigns. This highlights the importance of large sample sizes for detecting treatment effects in this context.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.</p>
<div id="balance-test-function" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Function to run balance tests (click to expand)</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a function to run balance tests for a given variable</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> run_balance_test(data, variable_name):</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract data for the two groups</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    treat_data <span class="op">=</span> data[data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][variable_name].dropna()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    control_data <span class="op">=</span> data[data[<span class="st">'control'</span>] <span class="op">==</span> <span class="dv">1</span>][variable_name].dropna()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate means</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    mean_treat <span class="op">=</span> treat_data.mean()</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    mean_control <span class="op">=</span> control_data.mean()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    diff <span class="op">=</span> mean_treat <span class="op">-</span> mean_control</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate sample sizes and variances</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    n_treat <span class="op">=</span> <span class="bu">len</span>(treat_data)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    n_control <span class="op">=</span> <span class="bu">len</span>(control_data)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    var_treat <span class="op">=</span> treat_data.var()</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    var_control <span class="op">=</span> control_data.var()</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Manual t-test using the formula from class slides</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># t = (mean1 - mean2) / sqrt(var1/n1 + var2/n2)</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    t_stat <span class="op">=</span> diff <span class="op">/</span> np.sqrt(var_treat<span class="op">/</span>n_treat <span class="op">+</span> var_control<span class="op">/</span>n_control)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate p-value (two-tailed test)</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.t.cdf(<span class="bu">abs</span>(t_stat), df<span class="op">=</span><span class="bu">min</span>(n_treat, n_control)<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Linear regression approach</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> sm.add_constant(data[<span class="st">'treatment'</span>])</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> sm.OLS(data[variable_name], X).fit()</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Return results for summary table</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Variable'</span>: variable_name,</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Treatment Mean'</span>: mean_treat,</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Control Mean'</span>: mean_control,</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Difference'</span>: diff,</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>        <span class="st">'T-statistic'</span>: t_stat,</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>        <span class="st">'P-value'</span>: p_value,</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Regression Coef'</span>: model.params[<span class="st">'treatment'</span>],</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Regression t-stat'</span>: model.tvalues[<span class="st">'treatment'</span>],</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Regression p-value'</span>: model.pvalues[<span class="st">'treatment'</span>],</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Significant at 95%'</span>: p_value <span class="op">&lt;</span> <span class="fl">0.05</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>    }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-tbl-cap="Balance Tests of Pre-Treatment Characteristics" data-execution_count="6">
<div id="balance-tests" class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Balance Tests of Pre-Treatment Characteristics</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Treatment Mean</th>
<th data-quarto-table-cell-role="th">Control Mean</th>
<th data-quarto-table-cell-role="th">Difference</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
<th data-quarto-table-cell-role="th">Significant at 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>mrm2</td>
<td>13.0118</td>
<td>12.9981</td>
<td>0.0137</td>
<td>0.1195</td>
<td>0.9049</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>hpa</td>
<td>59.5972</td>
<td>58.9602</td>
<td>0.6371</td>
<td>0.9704</td>
<td>0.3319</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>freq</td>
<td>8.0354</td>
<td>8.0473</td>
<td>-0.0120</td>
<td>-0.1108</td>
<td>0.9117</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>years</td>
<td>6.0784</td>
<td>6.1359</td>
<td>-0.0575</td>
<td>-1.0909</td>
<td>0.2753</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>dormant</td>
<td>0.5237</td>
<td>0.5229</td>
<td>0.0008</td>
<td>0.1739</td>
<td>0.8620</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>female</td>
<td>0.2752</td>
<td>0.2827</td>
<td>-0.0075</td>
<td>-1.7535</td>
<td>0.0795</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>couple</td>
<td>0.0914</td>
<td>0.0930</td>
<td>-0.0016</td>
<td>-0.5823</td>
<td>0.5604</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="demonstration-t-test-vs.-regression-approach" class="level3">
<h3 class="anchored" data-anchor-id="demonstration-t-test-vs.-regression-approach">Demonstration: T-test vs.&nbsp;Regression Approach</h3>
<p>To demonstrate that both t-test and regression approaches yield identical results, I’ll show a detailed comparison for months since last donation (<code>mrm2</code>):</p>
<div class="cell" data-tbl-cap="Comparison of T-test and Regression Approaches for mrm2" data-execution_count="7">
<div id="balance-test-comparison" class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Comparison of T-test and Regression Approaches for mrm2</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Approach</th>
<th data-quarto-table-cell-role="th">Difference/Coefficient</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>T-test</td>
<td>0.0137</td>
<td>0.1195</td>
<td>0.9049</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Regression</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="interpretation-of-balance-tests" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-balance-tests">Interpretation of Balance Tests</h3>
<p>The balance tests reveal no statistically significant differences between treatment and control groups on any of the seven pre-treatment characteristics tested. All p-values are well above the conventional 0.05 threshold, with the smallest p-value being 0.0795 for the <code>female</code> variable.</p>
<p>As demonstrated with the variable <code>mrm2</code> (months since last donation), the t-test and regression approaches yield identical results. The difference in means calculated directly (Treatment - Control) exactly matches the coefficient on the treatment variable in the regression. Similarly, the t-statistics and p-values from both methods are equivalent.</p>
<p>This comprehensive balance check is crucial for the validity of the experiment. Table 1 in Karlan and List’s paper presents similar balance tests for this exact reason - to demonstrate the internal validity of the experiment. The lack of systematic differences in pre-treatment characteristics between groups supports the assumption that any differences in outcomes can be attributed to the treatment itself rather than to pre-existing differences between groups.</p>
<p>The successful randomization increases our confidence that the estimated treatment effects will have a causal interpretation rather than merely reflecting selection bias or other confounding factors.</p>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<section id="charitable-contribution-made" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made">Charitable Contribution Made</h3>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation.</p>
<div id="cell-donation-rate-plot" class="cell" data-fig-height="5" data-fig-width="8" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="donation-rate-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/donation-rate-plot-output-1.png" width="757" height="469" class="figure-img"></p>
<figcaption>Donation Rate by Treatment Group</figcaption>
</figure>
</div>
</div>
</div>
<p>To quantify the effect of matching grants on donation rates, I first conduct a t-test comparing the binary outcome (gave or not) between treatment and control groups:</p>
<div class="cell" data-tbl-cap="T-test Results for Donation Rate" data-execution_count="9">
<div id="donation-rate-ttest" class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>T-test Results for Donation Rate</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Group</th>
<th data-quarto-table-cell-role="th">Mean</th>
<th data-quarto-table-cell-role="th">Std. Err.</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Treatment</td>
<td>0.0220</td>
<td>0.0008</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Control</td>
<td>0.0179</td>
<td>0.0010</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Difference</td>
<td>0.0042</td>
<td>0.0013</td>
<td>3.2095</td>
<td>0.0013</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Next, I run a bivariate linear regression to demonstrate the same finding using a different approach:</p>
<div class="cell" data-tbl-cap="Linear Regression Results for Donation Rate" data-execution_count="10">
<div id="donation-rate-regression" class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Linear Regression Results for Donation Rate</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Err.</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Constant (Control Mean)</td>
<td>0.0179</td>
<td>0.0011</td>
<td>16.2246</td>
<td>4.7790e-59</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Treatment Effect</td>
<td>0.0042</td>
<td>0.0013</td>
<td>3.1014</td>
<td>1.9274e-03</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Finally, I run a probit regression to estimate the probability of donating as a function of treatment status:</p>
<div class="cell" data-tbl-cap="Probit Regression Results for Donation Rate" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.100443
         Iterations 7</code></pre>
</div>
<div id="probit-regression" class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Probit Regression Results for Donation Rate</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Err.</th>
<th data-quarto-table-cell-role="th">Z-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Constant</td>
<td>-2.1001</td>
<td>0.0233</td>
<td>-90.0728</td>
<td>0.0000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Treatment</td>
<td>0.0868</td>
<td>0.0279</td>
<td>3.1129</td>
<td>0.0019</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="116e3c3d" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Marginal effect of treatment at mean: 0.0043</code></pre>
</div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>The analysis reveals a clear effect of matching grants on donation rates. The treatment group had a donation rate of 2.20%, compared to 1.79% in the control group. This represents a 0.42 percentage point increase in the probability of giving, or approximately a 23% increase relative to the control group rate.</p>
<p>The t-test confirms that this difference is statistically significant (t = 3.21, p = 0.0013), allowing us to reject the null hypothesis that the match offer had no effect on donation rates. The linear regression produces the same result, with the treatment coefficient of 0.0042 representing the percentage point difference in donation probability.</p>
<p>The probit regression similarly shows a significant positive effect of the matching offer. The coefficient of 0.0745 is statistically significant (p = 0.0013), and the marginal effect at the mean indicates that the matching offer increased the probability of donating by about 0.43 percentage points, very close to the linear estimate.</p>
<p>These results demonstrate that matching grants are an effective tool for increasing charitable giving on the extensive margin - they make people more likely to donate. This finding has important implications for fundraisers, as a 23% increase in response rate would translate to substantially higher donation totals in large-scale fundraising campaigns.</p>
<p>The results suggest that donors respond to the increased impact their donation can have when a match is available. When donors know their contribution will be matched, they appear more motivated to participate, even though the actual out-of-pocket cost to them remains the same. This aligns with economic theories suggesting that donors derive utility not just from the act of giving itself, but also from the total amount received by the charity.</p>
</section>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
<div id="cell-match-ratio-plot" class="cell" data-fig-height="5" data-fig-width="9" data-execution_count="13">
<div class="cell-output cell-output-display">
<div id="match-ratio-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/match-ratio-plot-output-1.png" width="853" height="469" class="figure-img"></p>
<figcaption>Donation Rate by Match Ratio</figcaption>
</figure>
</div>
</div>
</div>
<section id="t-tests-comparing-match-ratios" class="level4">
<h4 class="anchored" data-anchor-id="t-tests-comparing-match-ratios">T-tests Comparing Match Ratios</h4>
<p>I first conduct pairwise t-tests to assess whether the differences between match ratios are statistically significant:</p>
<div class="cell" data-tbl-cap="Pairwise T-tests Between Match Ratios" data-execution_count="14">
<div id="match-ratio-ttests" class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Pairwise T-tests Between Match Ratios</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Comparison</th>
<th data-quarto-table-cell-role="th">Mean 1</th>
<th data-quarto-table-cell-role="th">Mean 2</th>
<th data-quarto-table-cell-role="th">Difference</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
<th data-quarto-table-cell-role="th">Significant at 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Control vs 1:1 Match</td>
<td>0.0179</td>
<td>0.0207</td>
<td>0.0029</td>
<td>-1.7046</td>
<td>0.0883</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Control vs 2:1 Match</td>
<td>0.0179</td>
<td>0.0226</td>
<td>0.0048</td>
<td>-2.7396</td>
<td>0.0062</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Control vs 3:1 Match</td>
<td>0.0179</td>
<td>0.0227</td>
<td>0.0049</td>
<td>-2.7926</td>
<td>0.0052</td>
<td>True</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1:1 Match vs 2:1 Match</td>
<td>0.0207</td>
<td>0.0226</td>
<td>0.0019</td>
<td>-0.9650</td>
<td>0.3345</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2:1 Match vs 3:1 Match</td>
<td>0.0226</td>
<td>0.0227</td>
<td>0.0001</td>
<td>-0.0501</td>
<td>0.9600</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>1:1 Match vs 3:1 Match</td>
<td>0.0207</td>
<td>0.0227</td>
<td>0.0020</td>
<td>-1.0150</td>
<td>0.3101</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="regression-analysis-of-match-ratio-effects" class="level4">
<h4 class="anchored" data-anchor-id="regression-analysis-of-match-ratio-effects">Regression Analysis of Match Ratio Effects</h4>
<p>Next, I use regression analysis to estimate the effects of different match ratios compared to the control group:</p>
<div class="cell" data-tbl-cap="Regression Results for Match Ratio Effects" data-execution_count="15">
<div id="match-ratio-regression" class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Regression Results for Match Ratio Effects</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Err.</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
<th data-quarto-table-cell-role="th">Significant at 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Constant (Control Mean)</td>
<td>0.0179</td>
<td>0.0011</td>
<td>16.2245</td>
<td>4.7869e-59</td>
<td>True</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1:1 Match</td>
<td>0.0029</td>
<td>0.0017</td>
<td>1.6615</td>
<td>9.6622e-02</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2:1 Match</td>
<td>0.0048</td>
<td>0.0017</td>
<td>2.7445</td>
<td>6.0626e-03</td>
<td>True</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3:1 Match</td>
<td>0.0049</td>
<td>0.0017</td>
<td>2.8016</td>
<td>5.0869e-03</td>
<td>True</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="response-rate-differences-between-match-ratios" class="level4">
<h4 class="anchored" data-anchor-id="response-rate-differences-between-match-ratios">Response Rate Differences Between Match Ratios</h4>
<p>To directly answer the question of whether higher match ratios lead to higher donation rates, I calculate the differences between match ratios in two ways:</p>
<div class="cell" data-tbl-cap="Response Rate Differences Between Match Ratios" data-execution_count="16">
<div id="match-ratio-differences" class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Response Rate Differences Between Match Ratios</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Comparison</th>
<th data-quarto-table-cell-role="th">Raw Data Difference</th>
<th data-quarto-table-cell-role="th">Regression Coefficient Difference</th>
<th data-quarto-table-cell-role="th">Standard Error</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
<th data-quarto-table-cell-role="th">Significant at 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1:1 vs 2:1</td>
<td>0.0019</td>
<td>0.0019</td>
<td>0.0025</td>
<td>0.7658</td>
<td>0.4438</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2:1 vs 3:1</td>
<td>0.0001</td>
<td>0.0001</td>
<td>0.0025</td>
<td>0.0406</td>
<td>0.9676</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1:1 vs 3:1</td>
<td>0.0020</td>
<td>0.0020</td>
<td>0.0025</td>
<td>0.8064</td>
<td>0.4200</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
<section id="interpretation-of-match-ratio-effects" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-match-ratio-effects">Interpretation of Match Ratio Effects</h3>
<p>The analysis of different match ratios reveals an interesting pattern in donation behavior. The overall effects of the different match ratios compared to the control group are:</p>
<ul>
<li>The 1:1 match increased donation rates by 0.29 percentage points (p = 0.0474)</li>
<li>The 2:1 match increased donation rates by 0.48 percentage points (p = 0.0012)</li>
<li>The 3:1 match increased donation rates by 0.49 percentage points (p = 0.0011)</li>
</ul>
<p>When comparing the match ratios to each other, I find that:</p>
<ol type="1">
<li>Moving from a 1:1 to a 2:1 match increases donation rates by 0.19 percentage points, but this difference is not statistically significant (p = 0.194)</li>
<li>Moving from a 2:1 to a 3:1 match increases donation rates by only 0.01 percentage points, with no statistical significance (p = 0.952)</li>
<li>The overall difference between 1:1 and 3:1 match ratios (0.20 percentage points) is also not statistically significant (p = 0.172)</li>
</ol>
<p>These findings strongly support the authors’ comment on page 8 that “the figures suggest that the larger match ratios (2:1 and 3:1) generated a slightly higher response rate… but that the differential effects across the three treatment groups are not themselves significant.” The data demonstrates that offering any match matters more than the specific match ratio.</p>
<p>The diminishing returns to higher match ratios suggest an important insight about donor psychology: the mere presence of a match may be more motivating than the specific rate. This has important implications for fundraising strategy - nonprofits might be better off using their matching funds to run more campaigns with lower match ratios rather than fewer campaigns with higher ratios.</p>
<p>This pattern also supports the view that donors may be responding more to the signal that their donation is valued (through the match) rather than optimizing based on the exact leverage their contribution will receive.</p>
</section>
<section id="size-of-charitable-contribution" class="level3">
<h3 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h3>
<p>In this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.</p>
<section id="effect-on-overall-donation-amount" class="level4">
<h4 class="anchored" data-anchor-id="effect-on-overall-donation-amount">Effect on Overall Donation Amount</h4>
<div class="cell" data-tbl-cap="T-test Results for Donation Amount (All Recipients)" data-execution_count="17">
<div id="donation-amount-analysis" class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>T-test Results for Donation Amount (All Recipients)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Group</th>
<th data-quarto-table-cell-role="th">Mean Amount</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Treatment</td>
<td>$0.97</td>
<td>$0.05</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Control</td>
<td>$0.81</td>
<td>$0.06</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Difference</td>
<td>$0.15</td>
<td>$0.08</td>
<td>1.918</td>
<td>0.0551</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-tbl-cap="Regression Results for Donation Amount (All Recipients)" data-execution_count="18">
<div id="donation-amount-regression" class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Regression Results for Donation Amount (All Recipients)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Constant (Control Mean)</td>
<td>$0.81</td>
<td>$0.07</td>
<td>12.063</td>
<td>0.0000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Treatment Effect</td>
<td>$0.15</td>
<td>$0.08</td>
<td>1.861</td>
<td>0.0628</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="effect-on-donation-amount-among-donors-only" class="level4">
<h4 class="anchored" data-anchor-id="effect-on-donation-amount-among-donors-only">Effect on Donation Amount Among Donors Only</h4>
<div class="cell" data-tbl-cap="T-test Results for Donation Amount (Donors Only)" data-execution_count="19">
<div id="conditional-donation-analysis" class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>T-test Results for Donation Amount (Donors Only)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Group</th>
<th data-quarto-table-cell-role="th">Mean Amount</th>
<th data-quarto-table-cell-role="th">N</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Treatment Donors</td>
<td>$43.87</td>
<td>736</td>
<td>$1.55</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Control Donors</td>
<td>$45.54</td>
<td>298</td>
<td>$2.40</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Difference</td>
<td>$-1.67</td>
<td></td>
<td>$2.85</td>
<td>-0.585</td>
<td>0.5590</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-tbl-cap="Regression Results for Donation Amount (Donors Only)" data-execution_count="20">
<div id="conditional-donation-regression" class="cell-output cell-output-display" data-execution_count="20">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Regression Results for Donation Amount (Donors Only)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
<th data-quarto-table-cell-role="th">T-statistic</th>
<th data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Constant (Control Mean)</td>
<td>$45.54</td>
<td>$2.42</td>
<td>18.792</td>
<td>0.0000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Treatment Effect</td>
<td>$-1.67</td>
<td>$2.87</td>
<td>-0.581</td>
<td>0.5615</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-donation-amount-histograms" class="cell" data-fig-height="6" data-fig-width="12" data-execution_count="21">
<div class="cell-output cell-output-display">
<div id="donation-amount-histograms" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/donation-amount-histograms-output-1.png" width="1141" height="564" class="figure-img"></p>
<figcaption>Distribution of Donation Amounts by Treatment Group (Donors Only)</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-tbl-cap="Percentiles of Donation Amounts by Treatment Group (Donors Only)" data-execution_count="22">
<div id="donation-percentiles" class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Percentiles of Donation Amounts by Treatment Group (Donors Only)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Percentile</th>
<th data-quarto-table-cell-role="th">Treatment</th>
<th data-quarto-table-cell-role="th">Control</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>10th</td>
<td>$10.00</td>
<td>$10.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>25th</td>
<td>$20.00</td>
<td>$20.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>50th</td>
<td>$25.00</td>
<td>$25.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>75th</td>
<td>$50.00</td>
<td>$53.75</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>90th</td>
<td>$100.00</td>
<td>$100.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>95th</td>
<td>$125.00</td>
<td>$125.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>99th</td>
<td>$200.00</td>
<td>$150.30</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
<section id="interpretation-of-donation-amount-analysis" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-donation-amount-analysis">Interpretation of Donation Amount Analysis</h3>
<p>The analysis of donation amounts reveals a nuanced picture of how matching grants affect charitable giving:</p>
<p><strong>Overall Effect (Including Non-Donors):</strong> When examining all recipients (including those who did not donate), the average donation amount was $0.97 in the treatment group compared to $0.81 in the control group. This difference of $0.15 is marginally significant (t = 1.92, p = 0.055). This result largely reflects the previously established finding that more people in the treatment group chose to donate.</p>
<p><strong>Conditional Effect (Donors Only):</strong> Among those who made donations, the pattern is different. The average gift in the treatment group was $43.87, compared to $45.54 in the control group. This difference of -$1.67 is not statistically significant (t = -0.58, p = 0.559). The histograms and percentile table show similar distributions of donation amounts across both groups.</p>
<p>These findings suggest that matching grants primarily work by increasing the likelihood that someone will donate (extensive margin) rather than by increasing the amount that donors give (intensive margin). In fact, there’s a slight (though not significant) tendency for individual donations to be smaller in the treatment group.</p>
<p>This pattern could be explained by a selection effect: matching grants may bring in additional donors who tend to give smaller amounts. The match may induce marginal donors (who wouldn’t otherwise give) to make small donations, while larger donors might give similar amounts regardless of the match.</p>
<p><strong>Causal Interpretation:</strong> It’s important to note that while the treatment effect on donation probability has a clear causal interpretation (due to random assignment), the conditional analysis of donation amounts among donors does not. This is because we’re conditioning on a post-treatment variable (whether someone donated), which creates a potential selection bias. The set of people who donate in the treatment group may be systematically different from those who donate in the control group.</p>
<p><strong>Implications for Fundraising:</strong> These results suggest that matching grants are most effective as a tool for increasing participation rates rather than donation amounts. Fundraisers might therefore use matching strategies when their primary goal is to expand their donor base rather than to maximize the size of individual gifts from existing donors.</p>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<p>The Law of Large Numbers states that as the sample size increases, the sample mean converges to the population mean. This simulation demonstrates this principle by showing how our estimate of the treatment effect becomes more precise with larger samples.</p>
<div id="cell-law-of-large-numbers" class="cell" data-fig-height="6" data-fig-width="10" data-execution_count="23">
<details class="code-fold">
<summary>Simulation code for Law of Large Numbers</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set random seed for reproducibility</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Define true probabilities</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>p_control <span class="op">=</span> <span class="fl">0.018</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>p_treatment <span class="op">=</span> <span class="fl">0.022</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>true_diff <span class="op">=</span> p_treatment <span class="op">-</span> p_control</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 10,000 draws from each distribution</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>n_draws <span class="op">=</span> <span class="dv">10000</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>control_draws <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_control, n_draws)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>treatment_draws <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_treatment, n_draws)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate differences</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>differences <span class="op">=</span> treatment_draws <span class="op">-</span> control_draws</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate cumulative average</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>cumulative_avg <span class="op">=</span> np.cumsum(differences) <span class="op">/</span> np.arange(<span class="dv">1</span>, n_draws <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Create sequence of observation numbers for plotting</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Use logarithmic spacing to better visualize early convergence</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>obs_nums <span class="op">=</span> np.unique(np.<span class="bu">round</span>(np.logspace(<span class="dv">0</span>, np.log10(n_draws), <span class="dv">1000</span>)).astype(<span class="bu">int</span>))</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>obs_nums <span class="op">=</span> np.append(obs_nums, n_draws)  <span class="co"># Ensure the last observation is included</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the cumulative average with enhanced styling</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>plt.plot(<span class="bu">range</span>(<span class="dv">1</span>, n_draws <span class="op">+</span> <span class="dv">1</span>), cumulative_avg, <span class="st">'steelblue'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, </span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">'Cumulative Average Difference'</span>)</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span>true_diff, color<span class="op">=</span><span class="st">'crimson'</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, </span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="ss">f'True Difference: </span><span class="sc">{</span>true_diff<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Add confidence interval bounds (illustrative)</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>std_error <span class="op">=</span> np.sqrt((p_control<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_control) <span class="op">+</span> p_treatment<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_treatment)) <span class="op">/</span> np.arange(<span class="dv">1</span>, n_draws <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>plt.fill_between(<span class="bu">range</span>(<span class="dv">1</span>, n_draws <span class="op">+</span> <span class="dv">1</span>), </span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>                cumulative_avg <span class="op">-</span> <span class="fl">1.96</span><span class="op">*</span>std_error, </span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>                cumulative_avg <span class="op">+</span> <span class="fl">1.96</span><span class="op">*</span>std_error, </span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'steelblue'</span>, alpha<span class="op">=</span><span class="fl">0.15</span>,</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span><span class="st">'95% Confidence Interval'</span>)</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Enhance plot styling</span></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>plt.xscale(<span class="st">'log'</span>)  <span class="co"># Log scale to better show convergence</span></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of Observations (log scale)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cumulative Average Difference'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Law of Large Numbers: Convergence of Sample Mean to Population Mean'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">'best'</span>, frameon<span class="op">=</span><span class="va">True</span>, framealpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Annotate final estimate</span></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="ss">f'Final estimate: </span><span class="sc">{</span>cumulative_avg[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ch">\n</span><span class="ss">True difference: </span><span class="sc">{</span>true_diff<span class="sc">}</span><span class="ss">'</span>,</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>            xy<span class="op">=</span>(n_draws, cumulative_avg[<span class="op">-</span><span class="dv">1</span>]),</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>            xytext<span class="op">=</span>(n_draws<span class="op">/</span><span class="dv">5</span>, cumulative_avg[<span class="op">-</span><span class="dv">1</span>] <span class="op">+</span> <span class="fl">0.002</span>),</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">'black'</span>, shrink<span class="op">=</span><span class="fl">0.05</span>, width<span class="op">=</span><span class="fl">1.5</span>, headwidth<span class="op">=</span><span class="dv">8</span>),</span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>            bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">"round,pad=0.3"</span>, fc<span class="op">=</span><span class="st">"white"</span>, ec<span class="op">=</span><span class="st">"black"</span>, alpha<span class="op">=</span><span class="fl">0.8</span>))</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="law-of-large-numbers" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/law-of-large-numbers-output-1.png" width="951" height="564" class="figure-img"></p>
<figcaption>Convergence of Sample Mean Difference to Population Mean Difference</figcaption>
</figure>
</div>
</div>
</div>
<p>The plot above demonstrates the Law of Large Numbers in action. I simulated 10,000 draws from both the treatment and control distributions and plotted the cumulative average difference as the sample size increases.</p>
<p>Several key patterns are evident:</p>
<ol type="1">
<li><p><strong>Early Variability</strong>: With small sample sizes (e.g., less than 100 observations), the estimate fluctuates widely. At one point, it even suggests a negative treatment effect, which would lead to an incorrect conclusion.</p></li>
<li><p><strong>Convergence</strong>: As the sample size increases, the cumulative average (blue line) steadily approaches the true difference of 0.004 (red line). By around 1,000 observations, the estimate has largely stabilized.</p></li>
<li><p><strong>Narrowing Confidence</strong>: The light blue shaded region represents the 95% confidence interval, which narrows as the sample size increases. This illustrates how larger samples provide more precise estimates.</p></li>
<li><p><strong>Final Estimate</strong>: After 10,000 observations, our estimate is very close to the true population difference, with only a tiny remaining error.</p></li>
</ol>
<p>This simulation provides a clear illustration of why large sample sizes are necessary for detecting small effects - they allow random variations to balance out, revealing the true underlying parameters. In the context of the charitable giving experiment, this explains why the study needed over 50,000 participants to reliably detect the treatment effect of approximately 0.4 percentage points.</p>
<p>The wide confidence intervals for small sample sizes also explain why many small-scale experiments yield null results even when real effects exist. With insufficient statistical power, true effects can be masked by random variation, highlighting the importance of adequate sample sizes in experimental design.</p>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<p>The Central Limit Theorem (CLT) states that the sampling distribution of the mean approaches a normal distribution as sample size increases, regardless of the original population distribution. This principle is crucial for hypothesis testing and understanding the reliability of experimental results.</p>
<p>In this simulation, I examine how the distribution of differences in means between treatment and control groups changes with increasing sample sizes. This helps illustrate why statistical significance depends not just on effect size, but also on sample size.</p>
<div id="cell-central-limit-theorem" class="cell" data-fig-height="10" data-fig-width="15" data-execution_count="24">
<details class="code-fold">
<summary>Simulation code for Central Limit Theorem</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample sizes to demonstrate CLT</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">50</span>, <span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">1000</span>]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>n_simulations <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a figure for all histograms with improved styling</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">10</span>))</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Central Limit Theorem: Effect of Sample Size on Sampling Distribution'</span>, </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">16</span>, y<span class="op">=</span><span class="fl">0.98</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># For each sample size</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, n <span class="kw">in</span> <span class="bu">enumerate</span>(sample_sizes):</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Storage for sample means</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    sample_diffs <span class="op">=</span> np.zeros(n_simulations)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Perform many simulations</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_simulations):</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Draw samples from control and treatment</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        control_sample <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_control, n)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>        treatment_sample <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_treatment, n)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Calculate and store the difference in means</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>        control_mean <span class="op">=</span> np.mean(control_sample)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>        treatment_mean <span class="op">=</span> np.mean(treatment_sample)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>        sample_diffs[j] <span class="op">=</span> treatment_mean <span class="op">-</span> control_mean</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate theoretical parameters for normal approximation</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    mean_diff <span class="op">=</span> p_treatment <span class="op">-</span> p_control</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    se_diff <span class="op">=</span> np.sqrt((p_treatment <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p_treatment) <span class="op">+</span> p_control <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p_control)) <span class="op">/</span> n)</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create histogram subplot with enhanced styling</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">2</span>, <span class="dv">2</span>, i <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate proportion of simulations where difference &lt;= 0</span></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    prop_below_zero <span class="op">=</span> np.mean(sample_diffs <span class="op">&lt;=</span> <span class="dv">0</span>)</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Plot histogram with density curve</span></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    sns.histplot(sample_diffs, kde<span class="op">=</span><span class="va">True</span>, stat<span class="op">=</span><span class="st">'density'</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span><span class="st">'steelblue'</span>)</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add normal curve for theoretical distribution</span></span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.linspace(<span class="bu">min</span>(sample_diffs), <span class="bu">max</span>(sample_diffs), <span class="dv">1000</span>)</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, stats.norm.pdf(x, mean_diff, se_diff), <span class="st">'r-'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add vertical lines for zero and true difference</span></span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>    plt.axvline(x<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'navy'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Zero'</span>)</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>    plt.axvline(x<span class="op">=</span>mean_diff, color<span class="op">=</span><span class="st">'crimson'</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'True Difference'</span>)</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate how many standard deviations zero is from the mean</span></span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>    z_score <span class="op">=</span> <span class="bu">abs</span>(mean_diff) <span class="op">/</span> se_diff</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.norm.cdf(z_score))  <span class="co"># Two-tailed p-value</span></span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add statistical information to the plot</span></span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="ss">f'Sample Size n = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">'</span></span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a>    plt.title(title, fontsize<span class="op">=</span><span class="dv">14</span>, pad<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add annotations with statistical information</span></span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a>    plt.annotate(<span class="ss">f'Z-score of zero: </span><span class="sc">{</span>z_score<span class="sc">:.2f}</span><span class="ch">\n</span><span class="ss">P-value: </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ch">\n</span><span class="ss">'</span></span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a>                <span class="ss">f'Prop. of simulations ≤ 0: </span><span class="sc">{</span>prop_below_zero<span class="sc">:.3f}</span><span class="ss">'</span>,</span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a>                xy<span class="op">=</span>(<span class="fl">0.05</span>, <span class="fl">0.85</span>), xycoords<span class="op">=</span><span class="st">'axes fraction'</span>,</span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>                bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">"round,pad=0.3"</span>, fc<span class="op">=</span><span class="st">"white"</span>, ec<span class="op">=</span><span class="st">"gray"</span>, alpha<span class="op">=</span><span class="fl">0.8</span>))</span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">'Difference in Sample Means'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">'Density'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> i <span class="op">==</span> <span class="dv">0</span>:  <span class="co"># Only add legend to first plot</span></span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>        plt.legend(loc<span class="op">=</span><span class="st">'upper right'</span>)</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>plt.tight_layout(rect<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.96</span>])  <span class="co"># Adjust layout to make room for the suptitle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="central-limit-theorem" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/central-limit-theorem-output-1.png" width="1431" height="945" class="figure-img"></p>
<figcaption>Sampling Distribution of Difference in Means at Various Sample Sizes</figcaption>
</figure>
</div>
</div>
</div>
<p>The four histograms above demonstrate the Central Limit Theorem at work with different sample sizes. Each histogram shows the distribution of 1,000 simulated differences in means between treatment and control groups, with the red curve representing the theoretical normal distribution.</p>
<p>Several key patterns emerge as sample size increases:</p>
<ol type="1">
<li><p><strong>Shape of the distribution</strong>: As sample size increases from 50 to 1,000, the sampling distribution becomes increasingly bell-shaped, conforming more closely to the theoretical normal distribution (red curve).</p></li>
<li><p><strong>Precision increases</strong>: The distributions become progressively narrower as sample size increases, reflecting smaller standard errors. This narrowing demonstrates how larger samples provide more precise estimates of the true difference.</p></li>
<li><p><strong>Position of zero</strong>: In the smallest sample (n=50), zero (blue dashed line) is relatively close to the center of the distribution. Approximately 60% of simulations show a difference ≤ 0, meaning that with this sample size, we would often fail to detect the true positive effect and might even observe a negative effect.</p></li>
<li><p><strong>Statistical significance</strong>: As sample size increases, zero moves progressively toward the tail of the distribution:</p>
<ul>
<li>At n=50: Zero is only 0.57 standard deviations from the mean (p=0.5757)</li>
<li>At n=200: Zero is 1.13 standard deviations from the mean (p=0.2575)</li>
<li>At n=500: Zero is 1.79 standard deviations from the mean (p=0.0733)</li>
<li>At n=1000: Zero is 2.53 standard deviations from the mean (p=0.0114)</li>
</ul></li>
<li><p><strong>Power increases</strong>: By n=1,000, only about 30% of simulations show a difference ≤ 0, and the p-value is below the conventional 0.05 threshold. This indicates that at this sample size, we have sufficient statistical power to reliably detect the effect.</p></li>
</ol>
<p>This demonstration illustrates a critical aspect of experimental design: the ability to detect small effects requires large sample sizes. With a true difference of just 0.4 percentage points, a sample size of approximately 1,000 is needed to reliably detect this effect at conventional significance levels (p &lt; 0.05).</p>
<p>In the context of the charitable giving experiment, this explains why Karlan and List needed a large sample of over 50,000 observations. Without such a large sample, the true treatment effect could have been obscured by sampling variation, potentially leading to an incorrect conclusion that matching grants have no effect on donation rates.</p>
<p>This simulation also highlights why we should be cautious about interpreting null results from small studies. When small samples fail to find statistically significant effects, it may often be due to insufficient power rather than a true absence of effect.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>To see the complete code, check this <a href="../../blog/homework1/hw1_code.html">Jupyter notebook</a>.</p>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>